
import logging
import json
import pandas as pd
from typing import Dict, Any, List, Optional

from ..services.ollama_service import ollama_service
from ..services.prompt_templates import PYTHON_ANALYSIS_PROMPT, OLLAMA_CONFIGS
from ..services.python_executor import python_executor
from ..utils.json_extractor import extract_json_from_llm_response

logger = logging.getLogger(__name__)

class PythonAnalystAgent:
    """
    Agent that analyzes data by generating and executing Python code.
    Inspired by PandasAI's approach.
    """
    
    def __init__(self):
        self.service = ollama_service
        self.executor = python_executor
        # Use sql_generation config as base for precise code generation, or create new one
        self.config = OLLAMA_CONFIGS.get("sql_generation", {
            "temperature": 0.1,
            "num_predict": 2048
        })

    def analyze(self, query: str, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Analyze the dataframe based on the query.
        
        Args:
            query: User question
            df: Pandas DataFrame
            
        Returns:
            Result dictionary with output, figure, code, etc.
        """
        logger.info(f"🐍 Python Analysis for: '{query}'")
        
        try:
            # 1. Prepare Context
            columns_info = ", ".join([f"{col} ({dtype})" for col, dtype in df.dtypes.items()])
            sample_data = df.head(5).to_markdown()
            
            # 2. Build Prompt
            prompt = PYTHON_ANALYSIS_PROMPT.format(
                columns=columns_info,
                sample_data=sample_data,
                user_question=query
            )
            
            # 3. Generate Code
            response_text = self.service.generate_response(
                prompt=prompt,
                temperature=0.1, # Keep strict for code
                json_mode=True,
                task_type="code_generation"
            )
            
            # 4. Parse Response
            logger.info(f"DEBUG: Raw LLM response: {response_text}")
            result_json = extract_json_from_llm_response(response_text)
            code = result_json.get("code", "")
            explanation = result_json.get("explanation", "")
            
            if not code:
                raise ValueError("No code generated by LLM")
                
            logger.info(f"📝 Generated Python code:\n{code}")
            
            # 5. Execute Code
            execution_result = self.executor.execute_code(code, df)
            
            return {
                "success": execution_result["success"],
                "query": query,
                "code": code,
                "explanation": explanation,
                "output": execution_result["output"],
                "figure_json": execution_result["figure_json"],
                "error": execution_result["error"]
            }
            
        except Exception as e:
            logger.error(f"Python analysis failed: {e}")
            return {
                "success": False,
                "query": query,
                "error": str(e)
            }

# Singleton
python_analyst_agent = PythonAnalystAgent()
